os: windows
language: python
python:
  - "3.8.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
after_success:
  bash <(curl -s https://codecov.io/bash)
codecov:
  require_ci_to_pass: yes
script:
  - python test.py
