CODECOV_TOKEN="5a03afa7-23a4-45f1-b763-9623ca480a9c"

language: python
python:
  - "3.8.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  python test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
